pub const SHOUTS: &[&str] = &[
    "HAHAHAHAHAHAHA",
    "WAFFLE HOUSE ALL-STAR SPECIAL - $11.60",
    "Hey kid, I'm a computer",
    "Pork chop sandwiches",
    "Giv'em the stick",
    "You're not my dad",
    "Mr. Body Massage Machine... GO",
    "Don't giv'em the stick",
    "You tell me do things",
    "I just wanna ride my motorcy... cle",
    "Stop all the downloadin'",
    "Help Computer",
    "You, you're the ring leader",
    "You sure about that?",
    "I believe I knew your mother, son",
    "Johnny, do you play baseball?",
    "Don't forget your sandwiches",
    "Look at all your different colored hats",
    "1, 2... 3 uhhhhhhhhhhhhhhhhhhh",
];
