[package]
name = "baseline-snake"
version = "1.0.0"
edition = "2024"

[dependencies]
actix-web = "4"
aspirin = "0.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
log = "0.4"
env_logger = "0.11"
rand = "0.8"
thiserror = "1"
